# Generated by Django 3.2.9 on 2021-11-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.TextField(blank=True)),
                ('updated_at', models.TextField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.TextField(blank=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='user.user')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
