# Generated by Django 3.2.8 on 2021-10-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='created_at',
            field=models.TextField(default=1634624269.7387898),
        ),
    ]
