# Generated by Django 3.2.8 on 2021-10-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.TextField(default=1635720458.1418056),
        ),
    ]
