# Generated by Django 3.2.8 on 2021-10-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_diary_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.TextField(blank=True)),
                ('created_at', models.TextField(default=1634821084.8194792)),
                ('updated_at', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
